targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        enabled: false
      auto_route_generator:auto_router_generator:
        enabled: false
      injectable_generator:injectable_builder:
        enabled: false
      injectable_generator:injectable_config_builder:
        enabled: false